version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - LANGFLOW_URL=http://langflow:7860
    depends_on:
      - redis
      - langflow
    volumes:
      - ./app:/app/app
      - ./flows:/app/flows

  langflow:
    image: logspace/langflow:latest
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_DEFAULT_FLOWS_PATH=/app/flows
      - LANGFLOW_REDIS_HOST=redis
      - LANGFLOW_REDIS_PORT=6379
    volumes:
      - ./flows:/app/flows
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web-ui:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://app:8000
    volumes:
      - .:/app
    command: python -m http.server 3000
    depends_on:
      - app

volumes:
  redis_data:

networks:
  flowbit-network:
    driver: bridge
